# Generated by Django 4.1.2 on 2022-10-10 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('figma', '0001_initial'),
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titullo', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=450)),
                ('quantidade_de_cursos', models.IntegerField(default=0)),
                ('descricao_passo_1', models.TextField(default='', max_length=450)),
                ('descricao_passo_2', models.TextField(default='', max_length=450)),
                ('descricao_passo_3', models.TextField(default='', max_length=450)),
                ('status', models.CharField(choices=[('1', 'Planejamento'), ('2', 'Early Access'), ('3', 'Finalizada')], default='1', max_length=3)),
                ('cursos', models.ManyToManyField(to='cursos.curso')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projeto', to='figma.figma')),
            ],
        ),
    ]
