# Generated by Django 4.1.2 on 2022-10-11 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formacao',
            options={'verbose_name_plural': 'Formações'},
        ),
    ]
