# Generated by Django 4.1.2 on 2022-10-13 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formacoes', '0002_alter_formacao_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formacao',
            name='projeto',
        ),
    ]
