# Generated by Django 4.1.2 on 2022-10-13 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formacoes', '0003_remove_formacao_projeto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formacao',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='formacao',
            name='descricao_passo_1',
        ),
        migrations.RemoveField(
            model_name='formacao',
            name='descricao_passo_2',
        ),
        migrations.RemoveField(
            model_name='formacao',
            name='descricao_passo_3',
        ),
        migrations.RemoveField(
            model_name='formacao',
            name='quantidade_de_cursos',
        ),
    ]
