# Generated by Django 4.1.2 on 2022-10-10 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('figma', '0001_initial'),
        ('instrutores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('id_do_curso', models.CharField(default='0000', max_length=10)),
                ('descricao', models.TextField(max_length=450)),
                ('github', models.URLField()),
                ('status', models.CharField(choices=[('P', 'Pausado'), ('A', 'Andamento'), ('F', 'Finalizado')], default='P', max_length=1)),
                ('instrutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrutores.instrutor')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='figma.figma')),
            ],
        ),
    ]
