# Generated by Django 4.1.2 on 2022-10-12 00:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_curso_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='id_do_curso',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(0)]),
        ),
    ]
