# Generated by Django 4.1.2 on 2022-10-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_curso_pasta_do_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='status',
            field=models.CharField(choices=[('0', 'Projeto'), ('1', 'Roteiro'), ('2', 'Gravação'), ('3', 'Atividades'), ('4', 'Revisão'), ('5', 'Exportação'), ('6', 'Edição'), ('7', 'Transcrição'), ('8', 'Publicação')], default='0', max_length=1),
        ),
    ]
