# Generated by Django 4.1.2 on 2022-10-17 17:13

import cursos.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('figma', '0003_figma_status'),
        ('cursos', '0006_alter_curso_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='ano',
            field=models.IntegerField(default=2022, validators=[django.core.validators.MinValueValidator(1984), cursos.models.max_value_current_year], verbose_name='ano'),
        ),
        migrations.AddField(
            model_name='curso',
            name='trimestre',
            field=models.CharField(choices=[('1', '1T'), ('2', '2T'), ('3', '3T'), ('4', '4T')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='curso',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='figma.figma'),
        ),
    ]
