# Generated by Django 4.1.2 on 2022-10-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideias_de_projetos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideia',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
