# Generated by Django 4.1.2 on 2022-10-12 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figma', '0002_alter_figma_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='figma',
            name='status',
            field=models.CharField(choices=[('P', 'Pausado'), ('A', 'Andamento'), ('F', 'Finalizado')], default='P', max_length=1),
        ),
    ]
