# Generated by Django 4.1.2 on 2022-10-11 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alura_mais', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alura_mais',
            options={'verbose_name_plural': 'Alura+'},
        ),
    ]
