# Generated by Django 4.1.2 on 2022-10-12 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alura_mais', '0002_alter_alura_mais_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='alura_mais',
            name='categoria',
            field=models.CharField(choices=[('0', '---'), ('1', 'ANGULAR'), ('2', 'AUTOMAÇÃO E PERFORMANCE'), ('3', 'FRAMEWORK MVC'), ('4', 'HTML E CSS'), ('5', 'JAVASCRIPT'), ('6', 'JQUERY'), ('7', 'REACT'), ('8', 'WORDPRESS')], default='0', max_length=1),
        ),
    ]
