# Generated by Django 4.1.2 on 2022-10-11 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrutores', '0002_remove_instrutor_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrutor',
            options={'verbose_name_plural': 'Instrutoras(os)'},
        ),
    ]
