# Generated by Django 4.1.2 on 2022-10-11 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instrutores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possui_notebook_da_empresa', models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NAO')], default='NAO', max_length=3)),
                ('notebook', models.CharField(max_length=100)),
                ('tipo_de_camera', models.CharField(max_length=100)),
                ('tipo_de_microfone', models.CharField(max_length=100)),
                ('iluminacao', models.TextField(max_length=450)),
                ('instrutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrutores.instrutor')),
            ],
        ),
    ]
