# Generated by Django 4.1.2 on 2022-10-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('cargo', models.CharField(choices=[('0', '---'), ('1', 'Scuba'), ('2', 'Instrutor Jr'), ('3', 'Instrutor'), ('4', 'Web writing'), ('5', 'Didática'), ('6', 'Designer'), ('7', 'Editor'), ('8', 'Produção'), ('9', 'Scrum Master'), ('10', 'Product Owner'), ('11', 'Tech Lead'), ('12', 'Madrinha/Padrinho')], default='0', max_length=20)),
            ],
        ),
    ]
