# Generated by Django 4.1.2 on 2022-10-10 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instrutores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('publico_alvo', models.TextField(max_length=450)),
                ('link_doc', models.URLField()),
                ('status', models.CharField(choices=[('P', 'Pausado'), ('A', 'Andamento'), ('F', 'Finalizado')], default='P', max_length=1)),
                ('instrutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrutor', to='instrutores.instrutor')),
            ],
        ),
    ]
