# Generated by Django 4.1.2 on 2022-10-12 00:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0002_alter_artigo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='id_do_artigo',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(0)]),
        ),
    ]
